name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-24.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}

    env:
      ImageOS: ubuntu24 # equivalent to runs-on ubuntu-24.04
      SHELL: /bin/bash
      LANG: C.UTF-8
      NUMBER_OF_FLOWTESTS_IN_PARALLEL: 10

    strategy:
      matrix:
        otp: ['27.3.3']
        rebar3: ['3.24.0']
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: inotify-tools mosquitto netcat-traditional i2c-tools
          version: 1.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 compile
      - run: rebar3 do eunit, ct
